from pathlib import Path
import sys
import json
import os
import re
import shutil
from zoneinfo import ZoneInfo, ZoneInfoNotFoundError

if getattr(sys, "frozen", False):
    ROOT = Path(sys.executable).resolve().parent
else:
    ROOT = Path(__file__).resolve().parent.parent
CONFIG_DIR = ROOT / "config"
PROMPTS_DIR = ROOT / "prompts"
ENV_PATH = ROOT / ".env"

CONFIG_DIR.mkdir(exist_ok=True)
PROMPTS_DIR.mkdir(exist_ok=True)


def ask(prompt, default=None, allow_empty=False):
    while True:
        suffix = f" [{default}]" if default not in (None, "") else ""
        value = input(f"{prompt}{suffix}: ").strip()

        if not value and default is not None:
            return str(default)

        if value or allow_empty:
            return value

        print("값을 입력해주세요.")


def ask_yes_no(prompt, default=True):
    default_text = "Y/n" if default else "y/N"
    while True:
        value = input(f"{prompt} [{default_text}]: ").strip().lower()

        if not value:
            return default

        if value in ("y", "yes", "예", "ㅇ", "응"):
            return True

        if value in ("n", "no", "아니오", "ㄴ"):
            return False

        print("y 또는 n으로 입력해주세요.")


def ask_int(prompt, default, minimum=0, maximum=23):
    while True:
        value = ask(prompt, default)
        try:
            number = int(value)
        except ValueError:
            print("숫자로 입력해주세요.")
            continue

        if minimum <= number <= maximum:
            return number

        print(f"{minimum}~{maximum} 범위로 입력해주세요.")


def ask_float(prompt, default, minimum=0.0):
    while True:
        value = ask(prompt, default)
        try:
            number = float(value)
        except ValueError:
            print("숫자로 입력해주세요.")
            continue

        if number >= minimum:
            return number

        print(f"{minimum} 이상의 숫자를 입력해주세요.")


def slugify(value, fallback):
    value = (value or "").strip().lower()
    value = re.sub(r"[^0-9a-zA-Z가-힣_-]+", "_", value)
    value = value.strip("_")
    return value or fallback


def env_key_for_character(key):
    value = re.sub(r"[^0-9A-Za-z]+", "_", key.upper()).strip("_")
    return f"DISCORD_{value}_TOKEN"


def parse_csv(value):
    if not value.strip():
        return []
    return [item.strip() for item in value.split(",") if item.strip()]


def load_json(path, default):
    if not path.exists():
        return default

    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return default


def save_json(path, data):
    path.write_text(
        json.dumps(data, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )


def load_env_lines():
    result = {}
    if ENV_PATH.exists():
        for line in ENV_PATH.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, value = line.split("=", 1)
            result[key.strip()] = value.strip()
    return result


def save_env(values):
    order = [
        "OPENAI_API_KEY",
        "DISCORD_GUILD_ID",
        "DISCORD_STATUS_TOKEN",
        "DISCORD_STATUS_CHANNEL",
        "DISCORD_COMMAND_CHANNEL_ID",
        "DISCORD_PERSONAL_RP_GUILD_IDS",
    ]

    character_keys = sorted(
        key for key in values
        if key.startswith("DISCORD_")
        and key.endswith("_TOKEN")
        and key not in {"DISCORD_STATUS_TOKEN"}
    )

    lines = [
        "# Generated by setup_wizard.py",
        "",
    ]

    written = set()

    for key in order + character_keys:
        if key in values and key not in written:
            lines.append(f"{key}={values[key]}")
            written.add(key)

    for key, value in values.items():
        if key not in written:
            lines.append(f"{key}={value}")

    ENV_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")


def create_prompt_file(path, name):
    template = f"""[정체성]
이름: {name}
나이:
직업 / 역할:
출신:
현재 상황:

[성격]
-

[말투]
-

[외형]
-

[일상]
-

[좋아하는 것]
-

[싫어하는 것]
-

[목표]
-

[약점 / 모순]
-

[다른 캐릭터와의 관계]
- 이미 정해진 관계만 작성한다.
- 적지 않은 관계는 실제 상호작용을 통해 발전시킨다.

[역할의 중심]
- 이 캐릭터가 어떤 상황에서도 유지해야 할 핵심:
- 이 캐릭터가 변질되지 않도록 피해야 할 방향:
"""
    path.write_text(template, encoding="utf-8")



def ask_timezone(default="Asia/Seoul"):
    while True:
        value = ask(
            "RP 생활 시간대 (IANA 형식, 예: Asia/Seoul / America/New_York)",
            default,
        ).strip()

        try:
            ZoneInfo(value)
            return value
        except ZoneInfoNotFoundError:
            if value.lower() in ("asia/seoul", "kst"):
                # 봇 본체는 tzdata가 없어도 서울 시간 fallback을 지원한다.
                return "Asia/Seoul"
            if value.lower() in ("utc", "etc/utc", "gmt"):
                return "UTC"

            print(
                "이 Python 환경에서 해당 시간대를 찾지 못했습니다. "
                "Windows라면 `pip install tzdata` 후 다시 시도하거나 "
                "Asia/Seoul 또는 UTC를 사용해주세요."
            )


def main():
    print("=" * 60)
    print(" Generic Character Discord RP Bot - Setup Wizard v61")
    print("=" * 60)
    print()
    print("이 마법사는 .env, 캐릭터, 장소, 세계관 템플릿을 만들어줍니다.")
    print("기존 파일이 있으면 먼저 백업할 수 있습니다.")
    print()

    existing = any(
        (CONFIG_DIR / name).exists()
        for name in ("characters.json", "places.json", "settings.json", "relations.json")
    )

    if existing and ask_yes_no("기존 config 파일을 backup 폴더에 백업할까요?", True):
        backup_dir = ROOT / "backup_setup"
        backup_dir.mkdir(exist_ok=True)
        for filename in ("characters.json", "places.json", "settings.json", "relations.json"):
            path = CONFIG_DIR / filename
            if path.exists():
                shutil.copy2(path, backup_dir / filename)
        if ENV_PATH.exists():
            shutil.copy2(ENV_PATH, backup_dir / ".env")
        print(f"백업 완료: {backup_dir}")
        print()

    env_values = load_env_lines()

    print("[1/5] 기본 키 / 서버 설정")
    print("-" * 60)

    openai_key = ask(
        "OpenAI API Key (기존 값 유지 가능)",
        env_values.get("OPENAI_API_KEY", ""),
        allow_empty=True,
    )
    if openai_key:
        env_values["OPENAI_API_KEY"] = openai_key

    guild_id = ask(
        "본서버 Discord Guild ID",
        env_values.get("DISCORD_GUILD_ID", ""),
        allow_empty=True,
    )
    if guild_id:
        env_values["DISCORD_GUILD_ID"] = guild_id

    if ask_yes_no("상태봇도 사용할까요?", False):
        status_token = ask(
            "상태봇 토큰",
            env_values.get("DISCORD_STATUS_TOKEN", ""),
            allow_empty=True,
        )
        if status_token:
            env_values["DISCORD_STATUS_TOKEN"] = status_token

        env_values["DISCORD_STATUS_CHANNEL"] = ask(
            "상태 채널 이름",
            env_values.get("DISCORD_STATUS_CHANNEL", "캐릭터-상태"),
        )

    print()
    print("[2/5] 세계관 설정")
    print("-" * 60)

    old_settings = load_json(CONFIG_DIR / "settings.json", {})
    world_name = ask(
        "세계 이름",
        old_settings.get("world_name", "나의 RP 세계"),
    )
    world_description = ask(
        "세계 설명 (한 줄)",
        old_settings.get("world_description", ""),
        allow_empty=True,
    )

    rp_timezone = ask_timezone(
        old_settings.get("timezone", "Asia/Seoul"),
    )

    common_rules = []
    print("공통 규칙을 입력합니다. 빈 줄을 입력하면 끝납니다.")
    while True:
        rule = input("공통 규칙: ").strip()
        if not rule:
            break
        common_rules.append(rule)

    if not common_rules:
        common_rules = old_settings.get(
            "common_rules",
            [
                "설정에 없는 중대한 과거 사건이나 세계관 사실을 임의로 확정하지 않는다.",
                "사용자의 부탁은 명령이 아니며 캐릭터 성격에 따라 거절할 수 있다.",
                "항상 큰 사건만 만들지 말고 평범한 일상 대화도 자연스럽게 한다.",
            ],
        )

    print()
    print("기능 ON/OFF 설정")
    print("-" * 60)

    feature_questions = [
        ("world_simulation", "본서버 월드 시뮬레이션", True),
        ("place_movement", "캐릭터 장소 자동 이동", True),
        ("autonomous_messages", "자율발언 / 먼저 말걸기", True),
        ("bot_to_bot_chat", "캐릭터끼리 자동 대화", True),
        ("long_term_memory", "사용자/캐릭터 장기 기억", True),
        ("relationships", "관계 설정 및 관계 변화", True),
        ("personal_rp", "개인 RP 서버 지원", True),
        ("dm", "캐릭터 DM 대화", True),
        ("offline_mention_recovery", "오프라인 멘션 복구", True),
        ("sleep_system", "수면 시스템", True),
        ("away_system", "외출 시스템", True),
        ("appointments", "약속 시스템", True),
        ("dynamic_events", "캐릭터 다이나믹 이벤트", True),
        ("city_events", "도시/세계 이벤트", True),
        ("status_dashboard", "상태봇 대시보드", True),
        ("presence", "Discord 상태메시지", True),
    ]

    features = {}
    for key, label, default in feature_questions:
        features[key] = ask_yes_no(f"{label}을(를) 사용할까요?", default)

    print()
    print("Discord 채널 자동 생성 설정")
    create_categories = ask_yes_no(
        "장소 그룹별 카테고리를 자동 생성할까요?",
        True,
    )
    create_status_channel = ask_yes_no(
        "상태봇 사용 시 상태 채널도 자동 생성할까요?",
        True,
    )

    settings = {
        "world_name": world_name,
        "world_description": world_description,
        "timezone": rp_timezone,
        "common_rules": common_rules,
        "features": features,
        "channel_setup": {
            "create_categories": create_categories,
            "create_status_channel": create_status_channel,
            "category_names": {
                "public": "Public",
                "outdoor": "Outdoor",
                "private": "Private",
                "system": "System"
            }
        }
    }

    print()
    print("[3/5] 장소 설정")
    print("-" * 60)

    places = {}
    place_count = ask_int("공용 장소를 몇 개 만들까요?", 3, 1, 50)

    for index in range(1, place_count + 1):
        print()
        print(f"--- 장소 {index}/{place_count} ---")
        name = ask("장소 이름", f"장소 {index}")
        channel_name = ask(
            "Discord 채널 이름",
            slugify(name, f"place-{index}").replace("_", "-"),
        )
        description = ask(
            "장소 설명",
            f"{name}의 공용 공간.",
        )
        objects = parse_csv(
            ask(
                "주변 사물 (쉼표로 구분)",
                "의자, 테이블",
                allow_empty=True,
            )
        )
        group = ask("장소 그룹", "public", allow_empty=True)
        parent = ask("물리적 상위 장소 (없으면 Enter)", "", allow_empty=True)

        places[name] = {
            "channel_name": channel_name,
            "description": description,
            "objects": objects,
            "group": group or "public",
            "parent": parent or None,
            "allowed_characters": [],
            "time_multipliers": {
                "morning": ask_float("아침 방문 배율", 1.0),
                "day": ask_float("낮 방문 배율", 1.0),
                "evening": ask_float("저녁 방문 배율", 1.0),
                "night": ask_float("밤 방문 배율", 1.0),
                "late_night": ask_float("새벽 방문 배율", 0.5),
            },
        }

    print()
    print("[4/5] 캐릭터 설정")
    print("-" * 60)

    characters = {}
    character_count = ask_int("캐릭터를 몇 명 만들까요?", 2, 1, 50)
    used_keys = set()

    for index in range(1, character_count + 1):
        print()
        print(f"--- 캐릭터 {index}/{character_count} ---")

        name = ask("캐릭터 이름", f"캐릭터 {index}")
        key_default = slugify(name, f"character_{index}")
        key = ask("내부 캐릭터 키", key_default)

        key = slugify(key, f"character_{index}")
        base_key = key
        suffix = 2
        while key in used_keys:
            key = f"{base_key}_{suffix}"
            suffix += 1
        used_keys.add(key)

        token_env = env_key_for_character(key)
        token = ask(
            f"{name} Discord Bot Token",
            env_values.get(token_env, ""),
            allow_empty=True,
        )
        if token:
            env_values[token_env] = token

        prompt_file = f"prompts/{key}.txt"
        prompt_path = ROOT / prompt_file

        private_room = ask_yes_no(f"{name}에게 개인실을 만들까요?", True)
        private_room_name = (
            ask("개인실 이름", f"{name} 방")
            if private_room
            else None
        )

        sleep_start_h = ask_int("취침 시작 최소 시", 1, 0, 23)
        sleep_start_m = ask_int("취침 시작 최소 분", 0, 0, 59)
        sleep_end_h = ask_int("취침 시작 최대 시", 3, 0, 23)
        sleep_end_m = ask_int("취침 시작 최대 분", 0, 0, 59)

        wake_start_h = ask_int("기상 최소 시", 8, 0, 23)
        wake_start_m = ask_int("기상 최소 분", 0, 0, 59)
        wake_end_h = ask_int("기상 최대 시", 10, 0, 23)
        wake_end_m = ask_int("기상 최대 분", 0, 0, 59)

        inventory = parse_csv(
            ask("기본 소지품 (쉼표 구분)", "", allow_empty=True)
        )
        habits = parse_csv(
            ask(
                "일상 습관 (쉼표 구분)",
                "쉬면서 주변을 살핌, 사람들과 가볍게 대화함",
                allow_empty=True,
            )
        )
        goals = parse_csv(
            ask(
                "장기 목표 (쉼표 구분)",
                "",
                allow_empty=True,
            )
        )

        print("장소별 방문 가중치를 설정합니다.")
        place_weights = {}
        for place_name in places:
            default_weight = 5.0
            place_weights[place_name] = ask_float(
                f"  {place_name} 가중치",
                default_weight,
            )

        if private_room_name:
            place_weights[private_room_name] = ask_float(
                f"  {private_room_name} 가중치",
                14.0,
            )

        restricted = parse_csv(
            ask(
                "출입 금지 장소 (쉼표 구분, 없으면 Enter)",
                "",
                allow_empty=True,
            )
        )

        characters[key] = {
            "name": name,
            "token_env": token_env,
            "prompt_file": prompt_file,
            "private_room": private_room_name,
            "sleep_start_range": [
                [sleep_start_h, sleep_start_m],
                [sleep_end_h, sleep_end_m],
            ],
            "wake_range": [
                [wake_start_h, wake_start_m],
                [wake_end_h, wake_end_m],
            ],
            "inventory": inventory,
            "habits": habits,
            "goals": goals,
            "place_weights": place_weights,
            "restricted_places": restricted,
        }

        if not prompt_path.exists() or ask_yes_no(
            f"{prompt_file} 프롬프트 템플릿을 새로 만들까요?",
            not prompt_path.exists(),
        ):
            create_prompt_file(prompt_path, name)
            print(f"프롬프트 템플릿 생성: {prompt_file}")

    print()
    print("[5/5] 캐릭터 초기 관계")
    print("-" * 60)

    relations = {}
    character_keys = list(characters)

    if len(character_keys) >= 2 and ask_yes_no(
        "캐릭터끼리 초기 관계도 지금 입력할까요?",
        True,
    ):
        for i, a in enumerate(character_keys):
            for b in character_keys[i + 1:]:
                a_name = characters[a]["name"]
                b_name = characters[b]["name"]

                if ask_yes_no(
                    f"{a_name} ↔ {b_name} 관계를 지정할까요?",
                    False,
                ):
                    context = ask(
                        "관계 설명",
                        "서로 알고 지내는 사이이며 구체적인 관계는 실제 상호작용을 통해 발전한다.",
                    )
                    relations[f"{a}|{b}"] = {
                        "context": context,
                    }

    save_json(CONFIG_DIR / "characters.json", characters)
    save_json(CONFIG_DIR / "places.json", places)
    save_json(CONFIG_DIR / "settings.json", settings)
    save_json(CONFIG_DIR / "relations.json", relations)
    save_env(env_values)

    print()
    print("=" * 60)
    print("설정 완료")
    print("=" * 60)
    print(f"- 캐릭터: {len(characters)}명")
    print(f"- 공용 장소: {len(places)}개")
    print(f"- 초기 관계: {len(relations)}개")
    print("- .env 저장 완료")
    print()
    print("다음 단계:")
    print("1. prompts 폴더의 캐릭터 프롬프트를 원하는 만큼 자세히 작성")
    print("2. Discord 서버에 characters.json의 channel_name과 같은 채널 생성")
    print("3. run_bot_v64.bat 실행")
    print()


if __name__ == "__main__":
    main()